pipeline{
	agent any

stages{
	
stage('hello'){
	
	steps{
	
	sh'''
	echo "Hello This is our first project"
	uptime
	date
	'''
	
	}
	}

stage('muni'){
	
	steps{
	
	sh'''
	echo "Hello This is muniraj"
	uptime
	date
	'''
	
	}
	}
stage('pooja'){
	
	steps{
	
	sh'''
	echo "Hello This is pooja muniraj"
	uptime
	date
	'''
	}
	}
stage('manoj'){
	
	steps{
	
	sh'''
	echo "Hello This is manoj"
	uptime
	date
	'''
	}
	}


	}
	}