pipeline{
	agent any

	stages{
	stage('hello'){
	steps{
	sh'''
	uptime
	date
	echo "hello world!!!"
	'''
	}
	}

stage('muni'){
	steps{
	sh'''
	uptime
	date
	echo "hello muni!!!"
	'''
	}

	}
stage('pooja'){
	steps{
	sh'''
	uptime
	date
	echo "hello pooja!!!"
	'''
	}

	}

stage('main'){
	steps{
	sh'''
	uptime
	date
	echo "hello main!!!"
	'''
	}

	}
stage('dev'){
	steps{
	sh'''
	uptime
	date
	echo "hello dev!!!"
	'''
	}

	}	
	}
}