pipeline{

    agent any

    stages{
        stage('git-checkout'){
            steps{
                git url : 'https://github.com/muniraj-git/Git-Test1.git', branch: 'main'
            }
        }
    }
}