pipeline{

    agent any

    parameters {
        string(name: 'ENV',defaultValue: 'Prod',description: 'Environment to deploy')
    }

    stages{

        stage('Deploy'){
            steps{
                echo "Deploying to ${params.ENV} environment"
            }
        }
    }
}